name: CI

on: 
  push:
    branches:    
    - master
  pull_request:
    branches:
    - master

jobs:
  example:
    runs-on: ubuntu-20.04
    steps:
      - uses: MeilCli/setup-crystal-action@v3
        with: 
          crystal_version: latest
          shards_version: latest
      - name: Run Crystal
        run: |
          echo 'puts "Hello Crystal"' > hello.cr
          crystal run hello.cr